### ISSUE TITLE
使用lneditor批量导出txt后，生成的txt文件导入不了（显示成功但没生成cst文件）

### ISSUE THREAD

**Issue by yzyi0320** [Dir-A/Hakuchuumu_CN_Patch#1]
强迫症想把HS部分汉化一下但改了之后发现封不回去了，顺带发现没改的用ineditor也封不起来。使用官方的mc.exe好像要用utf-8格式直接好像也不行。有没有什么更好的工具。

**Comment by yzyi0320** [comment]
试了下，读取不了gbk编码

**Comment by Dir-A** [comment]
> 试了下，读取不了gbk编码，utf-8好像也不行，源文本解出来好像是utf-16的
[CatSystemEditor_GBK.zip](https://github.com/Dir-A/Hakuchuumu_CN_Patch/files/8116919/CatSystemEditor_GBK.zip)
试试这个

**Comment by yzyi0320** [comment]
非HS部分未汉化（例如c01_04的部分）是因为官中也没汉化吗？

**Comment by Dir-A** [comment]
> 非HS部分未汉化（例如c01_04的部分）是因为官中也没汉化吗？

一般是这样，也有可能是因为官中少了句子，或者因为两边译文对不上被我删了，

**Comment by eventhorizonsky** [comment]
你好，我想请问翻译的进度如何了，我也想帮一点忙

**Comment by yzyi0320** [comment]
> 你好，我想帮我翻译一下如何了，我也想帮忙一点
完整的翻完的就c00_h_01和c01_h_00，其他的还鸽着。

**Comment by TBKing0520** [comment]
> 想

您好！请问现在翻译的进度如何？如果您没有时间精力继续进行补充翻译的话，可以把已经翻译的文件交予我吗？我们打算翻译完所有缺失部分，并且得到了本补丁作者的使用许可

**Comment by TBKing0520** [comment]
> > 你好，我想帮我翻译一下如何了，我也想帮忙一点
> > 完整的翻完的就c00_h_01和c01_h_00，其他的还鸽着。

您好！请问现在翻译的进度如何？如果您没有时间精力继续进行补充翻译的话，可以把已经翻译的文件交予我吗？我们打算翻译完所有缺失部分，并且得到了本补丁作者的使用许可。

**Comment by TBKing0520** [comment]
> > 你好，我想帮我翻译一下如何了，我也想帮忙一点
> > 完整的翻完的就c00_h_01和c01_h_00，其他的还鸽着。

另请问您还愿意参与补丁的制作吗？我们有翻译的人员，但还需要有补丁制作经验的dalao
