### ISSUE TITLE
About the game's tips

### ISSUE THREAD

**Issue by Cosetto** [Dir-A/Hakuchuumu_CN_Patch#3]
Not relate to your project but I just wonder how to extract to game's tips which is in .qdb file in qdb.int, I believe. Is there any tool to extract and recompile it?
![image](https://user-images.githubusercontent.com/81801486/172388461-916e15b9-74c0-4b87-8c89-0abd98e3aea4.png)

**Comment by Dir-A** [comment]
Hi Bro，I have no idea about the tools for this，but I can tell you that .qdb is the same as fes or kcs.  
.qdb using zlin compression，and Text encoding as UTF8（Chinese）
![QQ截图20220609002527](https://user-images.githubusercontent.com/79064817/172668333-ea07ade8-054c-489e-99bb-09ba2ed0eb4a.png)
you can refer to this project https://github.com/regomne/chinesize/tree/master/CatSystem2  
exkcs.py exfes.py to extract .qdb and repack it.

**Comment by Cosetto** [comment]
Thanks man

**Comment by Cosetto** [comment]
https://github.com/jszhtian/CS2Editor/blob/master/fesTools/fesTools/Program.cs There's also this tool uses to decode for catsystem2 that I found
